movies =[
   "john wick 1"
    "john wick 2"
    "john wick 3"
   " john wick 4"
   " harry potter"
    "jame bond"
   " hera pheri"
    "kon mil gaya jadoo"
   " the american pscyo"
    "Dilwale Dulhania Le Jayenge"
2."Sholay"
3. "3 Idiots"
4." Lagaan"
5. "PK"
6. "Dil Chahta Hai"
7. "Kabhi Khushi Kabhie Gham"
8." Zindagi Na Milegi Dobara"
9. "Queen"
10. "Bajrangi Bhaijaan"
11. "Gully Boy"
12." Dangal"
13. "Jab We Met"
14." Andaz Apna Apna"
 "Devdas"
16." Padmaavat"
" Bahubali: The Beginning"
" Bahubali 2: The Conclusion"
"Chak De! India"
" Kaho Naa... Pyaar Hai"
]